AnomalyDetection/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url


urlpatterns = [
    # url(r'^$',admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^SampleManage/',include('SampleManage.urls')),
]


admin.site.site_header = "Anomaly Decetion"
admin.site.site_title = "Anomaly Decetion"
admin.site.index_title = "Welcome to Anomaly Decetion"

SampleManage/urls.py
from django.urls import path
from . import views

app_name = 'SampleManage'
urlpatterns = [
     path('', views.index, name='index'),
     path('upload',views.upload,name='upload'),
     path('resultechart',views.resultechart,name = 'resultechart'),
     path('testform',views.testform,name='testform'),
     path('visualize',views.visualize,name='visualize'),
     path('visualizees', views.visualizees, name='visualizees'),
     path('predict',views.predict,name='predict'),
     path('detectes',views.detectes,name='detectes'),
     path('predictes',views.predictes,name='predictes'),
     path('<path:pathtest>/retag',views.retag,name='retag'),
     path('<path:pathtest>/retages',views.retages,name='retages'),
     path('train',views.train,name='train'),
     path('mulvisualize',views.mulvisualize,name='mulvisualize'),
     path('testform',views.testform,name='testform'),
     path('comparees',views.comparees,name='comparees')
]

SampleManage/models.py
from django.db import models

# Create your models here.
#metrics
# bytes_in_value, bytes_out_value,\
# cpu_idle_value, disk_free_value,\
# load_fifteen_value, load_five_value,\
# load_one_value, mem_buffers_value,\
# mem_cached_value, mem_free_value,\
# pkts_in_value, pkts_out_value,\
# proc_run_value, proc_total_value, \
# swap_free_value\

#原始样本数据库
class PriSample(models.Model):
    nodename = models.CharField(max_length=100)
    timestamp = models.DateTimeField(max_length=100)
    bytes_in_value = models.FloatField(max_length=20,null=True,blank=True)
    bytes_out_value = models.FloatField(max_length=20,null=True,blank=True)
    cpu_idle_value = models.FloatField(max_length=20,null=True,blank=True)
    disk_free_value = models.FloatField(max_length=20,null=True,blank=True)
    load_fifteen_value = models.FloatField(max_length=20,null=True,blank=True)
    load_five_value = models.FloatField(max_length=20,null=True,blank=True)
    load_one_value = models.FloatField(max_length=20,null=True,blank=True)
    mem_buffers_value = models.FloatField(max_length=20,null=True,blank=True)
    mem_cached_value = models.FloatField(max_length=20,null=True,blank=True)
    mem_free_value = models.FloatField(max_length=20,null=True,blank=True)
    pkts_in_value = models.FloatField(max_length=20,null=True,blank=True)
    pkts_out_value = models.FloatField(max_length=20,null=True,blank=True)
    proc_run_value = models.FloatField(max_length=20,null=True,blank=True)
    proc_total_value = models.FloatField(max_length=20,null=True,blank=True)
    swap_free_value = models.FloatField(max_length=20,null=True,blank=True)
    STATUS_NORMAL = 1
    STATUS_ANOMALY = -1
    STATUS_UNKNOW = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_ANOMALY, '异常'),
        (STATUS_UNKNOW, '未标记'),
    )
    label = models.IntegerField(default=STATUS_UNKNOW, choices=STATUS_ITEMS)

    class Meta:
        db_table = 'sampledb'
        ordering = ['nodename','timestamp']
        unique_together = [['nodename','timestamp']]

#预处理样本数据库
class ProSample(models.Model):
    nodename = models.CharField(max_length=100)
    timestamp = models.DateTimeField(max_length=100)
    bytes_in_value = models.FloatField(max_length=20,null=True,blank=True)
    bytes_out_value = models.FloatField(max_length=20,null=True,blank=True)
    cpu_idle_value = models.FloatField(max_length=20,null=True,blank=True)
    disk_free_value = models.FloatField(max_length=20,null=True,blank=True)
    load_fifteen_value = models.FloatField(max_length=20,null=True,blank=True)
    load_five_value = models.FloatField(max_length=20,null=True,blank=True)
    load_one_value = models.FloatField(max_length=20,null=True,blank=True)
    mem_buffers_value = models.FloatField(max_length=20,null=True,blank=True)
    mem_cached_value = models.FloatField(max_length=20,null=True,blank=True)
    mem_free_value = models.FloatField(max_length=20,null=True,blank=True)
    pkts_in_value = models.FloatField(max_length=20,null=True,blank=True)
    pkts_out_value = models.FloatField(max_length=20,null=True,blank=True)
    proc_run_value = models.FloatField(max_length=20,null=True,blank=True)
    proc_total_value = models.FloatField(max_length=20,null=True,blank=True)
    swap_free_value = models.FloatField(max_length=20,null=True,blank=True)
    STATUS_NORMAL = 1
    STATUS_ANOMALY = -1
    STATUS_UNKNOW = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_ANOMALY, '异常'),
        (STATUS_UNKNOW, '未标记'),
    )
    label = models.IntegerField(default=STATUS_UNKNOW, choices=STATUS_ITEMS)
    class Meta:
        db_table = 'prosampledb'
        ordering = ['nodename','timestamp']
        unique_together = [['nodename','timestamp']]


#Metrics
class Metric(models.Model):
    metric = models.CharField(max_length=30)
    class Meta:
        db_table = 'metric'

#Nodenames
class Nodename(models.Model):
    nodename = models.CharField(max_length=60)
    class Meta:
        db_table = 'nodename'

#Algorithm
#包括所有预测和检测算法，算法ID,算法名称，算法类型（预测/检测）,是否需要提前训练，参数
class Algorithm(models.Model):
    algorithmid = models.IntegerField(primary_key=True)
    algorithmname = models.CharField(max_length=50)

    PREDICT_ALGOTITHM = 0
    DETECT_ALGORITHM = 1
    TYPE_ITEMS = (
        (PREDICT_ALGOTITHM, '预测'),
        (DETECT_ALGORITHM,'检测')
    )
    algorithmtype = models.IntegerField(default=PREDICT_ALGOTITHM, choices=TYPE_ITEMS)

    TRAIN_NO = 0
    TRAIN_YES = 1
    ISTRAIN_ITEMS = (
        (TRAIN_NO,'无需训练模型'),
        (TRAIN_YES,'需训练模型')
    )
    istrain = models.IntegerField(default=TRAIN_NO,choices=ISTRAIN_ITEMS)

    algorithmparameter = models.CharField( max_length=300)

    class Meta:
        db_table = 'algorithm'

class PredictMethod(models.Model):
    methodname = models.CharField(max_length=50)
    algorithm = models.CharField(max_length=50)
    paramvalue = models.CharField(max_length=3000)
    path = models.CharField(max_length=100)
    class Meta:
        db_table = 'predictmethod'

class DetectMethod(models.Model):
    methodname = models.CharField(max_length=50)
    algorithm = models.CharField(max_length=50)
    paramvalue = models.CharField(max_length=3000)
    path = models.CharField(max_length=100)
    class Meta:
        db_table = 'detectmethod'

class Mulvisualize(models.Model):
    dedimensionname = models.CharField(max_length=50,primary_key=True)
    dedimensionalgorithm = models.CharField(max_length=50)
    dedimensionnodelist = models.CharField(max_length=1000)
    dedimensionmetrics = models.CharField(max_length=1000)
    dedimensionalparamvalue = models.CharField(max_length=300)
    dedimensionpath = models.CharField(max_length=100)
    class Meta:
        db_table = 'dedimension'

SampleManage/views.py
from django.shortcuts import render
from django.http import HttpResponse
import Common.sql_setting
import pandas as  pd
from sqlalchemy import create_engine
from django.contrib.auth.decorators import  login_required
import json
from .forms import PriSampleForm,VisualizeForm,VisualizeESForm,PredictVisForm,TrainForm,MulvisualizeForm,PredictVisesForm,TagForm,DetectVisesForm,CompareESForm
from .modelsql import modelsql
from algorithm.univariate_predictor.lstm import LSTM_mul_es_class
from algorithm.detection.Iforest import Iforest_class
from algorithm.model_setting import  Metrics
from algorithm.univariate_predictor.ewma import EWMA_class
from algorithm.univariate_predictor.swa import SWA_class
from algorithm.univariate_predictor.linearregression import  LR_class
from algorithm.univariate_predictor.arima import Arima_class
from algorithm.univariate_predictor.evaluation import evaluation
from algorithm.univariate_predictor import evaluation
import numpy as np
from .models import PriSample,ProSample,PredictMethod,DetectMethod
from algorithm.detection.Nsigma import Nsigma
from algorithm.detection.Qfunction import Qfunction
from sklearn.manifold import TSNE
from sklearn.preprocessing import MinMaxScaler
from esconn import esinteracton
import datetime,time
# from .format import DecimalEncoder
# Create your views here.


def index(request):
    return render(request, 'SampleManage/index.html')

@login_required
def upload(request):
    if request.method == "GET":
        return render(request,"SampleManage/index.html")
    else:
        #获取上传的样本文件，并对其进行分析
        myFile = request.FILES.get("uploadfile",None)
        #若上传空文件，则..
        if not myFile:
            return HttpResponse("no files for upload!")
        #过滤文件类型
        if not myFile.name.endswith('.csv'):
            return HttpResponse("请选择.csv文件")
        #处理文件
        file_data = pd.read_csv(myFile)
        file_data.replace('Array', np.nan, inplace=True)
        file_data = file_data.astype(object).where(pd.notnull(file_data), None)
        print(file_data)
        s = file_data.columns.values
        print(s)
        print(type(s))
        if not ((s[0] == 'nodename')&(s[1] == 'timestamp')):
            return HttpResponse("文件输入格式错误")
        file_data['timestamp'] = pd.to_datetime(file_data['timestamp'],errors='coerce',exact=False,infer_datetime_format=False)
        if (file_data['timestamp'].isnull().any()):
            print(file_data['timestamp'][0])
            return HttpResponse("存在错误的时间戳")
        if(file_data[file_data.duplicated('timestamp')].empty == False):
            return HttpResponse("存在重复的时间戳")
        print(type(file_data['timestamp'][0]))
        database_url = Common.sql_setting.DATABASE_URL
        engine = create_engine(database_url,echo=False)
        entries = []
        repeat = []
        testnum = 0
        for e in file_data.T.to_dict().values():
            if(PriSample.objects.filter(nodename=e['nodename'],timestamp=e['timestamp']).exists()):
                repeat.append([e['nodename'],e['timestamp']])
            else :
                testnum = testnum + 1
                entries.append(PriSample(**e))
        print(testnum)
        PriSample.objects.bulk_create(entries)

            # for e in ds.T.to_dict().values():
            #    PriSample.objects.get_or_create(metrics=e['metrics'],nodename=e['nodename'],timestamp=e['timestamp'],value=e['value'])

            #way2利用pandas to_sql批量导入数据
            # ds.to_sql("sample",con=engine,if_exists='replace')


        return render(request,'SampleManage/uploadsuccess.html',{'repeat':repeat})

def resultechart(request):
    return render(request,'SampleManage/resultechart.html')


#可视化元数据
def visualize(request):
    list = []
    anomalylist = []
    nodename = ''
    metric = ''
    obj = VisualizeForm()
    if request.method == "POST":
        obj = VisualizeForm(request.POST,request.FILES)
        if obj.is_valid():
            nodename = obj.clean()['nodenames']
            metric = obj.clean()['metrics']
            modeldata = modelsql(PriSample)
            list = modeldata.select_visualize_data(nodename=nodename,metric=metric)
            anomalylist = modeldata.select_visualize_anomaly(nodename=nodename,metric=metric)
        else:
            errors = obj.errors
        return render(request,'SampleManage/visualize.html',{'list':json.dumps(list),'anomalylist':json.dumps(anomalylist),'nodename':nodename,'metric':metric,'form':obj,})
    else:
        return render(request,'SampleManage/visualize.html',{'list':json.dumps(list),'anomalylist':json.dumps(anomalylist),'nodename':nodename,'metric':metric,'form':obj,})

def visualizees(request):
    edatasets = []
    nodename = ''
    metric = ''
    obj = VisualizeESForm()
    if request.method == "POST":
        obj = VisualizeESForm(request.POST,request.FILES)
        if obj.is_valid():
            nodename = obj.clean()['nodenames']
            metric = obj.clean()['metrics']
            start = obj.clean()['start']
            end = obj.clean()['end']
            metriclist = [metric]
            start = int(round(time.mktime(start.timetuple()))*1000)
            end = int(round(time.mktime(end.timetuple())) * 1000)
            source = esinteracton.search_nodename_timestamp_dataframe(nodename=nodename,starttime=start,endtime=end,metrics=metriclist)
            edatasets = [['timestamp', metric]]
            for i in range(len(source)):
                edataset = []
                edataset.append(source['timestamp'][i].strftime('%Y-%m-%d %H:%M:%S'))
                edataset.append(source[metric][i])
                edatasets.append(edataset)
        else:
            errors = obj.errors
        return render(request,'SampleManage/visualizees.html',{'list':json.dumps(edatasets),'nodename':nodename,'metric':metric,'form':obj,})
    else:
        return render(request,'SampleManage/visualizees.html',{'list':json.dumps(edatasets),'nodename':nodename,'metric':metric,'form':obj,})

#提供给数据人工打标的功能
def retag(request,pathtest):
    # nodename = request.POST.get('nodename')
    list = str.split(pathtest,'/')
    nodename = list[0]
    timestamp = list[1]
    timestamp = datetime.datetime.strptime(timestamp,'%Y-%m-%d %H:%M:%S')
    sample = PriSample.objects.get(nodename=nodename,timestamp=timestamp)
    if(request.method == 'GET'):
        form = PriSampleForm(instance=sample)
        context = {'pathtest':pathtest,'form':form}
        return render(request,'SampleManage/retag.html',context)
    if(request.method == 'POST'):
        form = PriSampleForm(request.POST,instance=sample)
        form.save()
        return HttpResponse('保存成功')

def retages(request,pathtest):
    # nodename = request.POST.get('nodename')
    list = str.split(pathtest,'/')
    nodename = list[0]
    timestamp = list[1]
    timestamp_ = datetime.datetime.strptime(timestamp,'%Y-%m-%d %H:%M:%S')
    form = TagForm()
    if(request.method == 'GET'):
        timestamp = int(round(time.mktime(timestamp_.timetuple())) * 1000)
        result = esinteracton.search_isexist(index="mlganglia_agg",
                                             query_json=esinteracton.search_nodename_timestamp_mantag_queryjson(nodename=nodename,timestamp=timestamp))
        if (result == 0):
            form = TagForm(initial={'nodename':nodename,'timestamp':timestamp_,'mantag':'0'})
        elif(result == 1):
            form = TagForm(initial={'nodename':nodename,'timestamp':timestamp_,'mantag':'1'})
        context = {'pathtest':pathtest,'form':form}
        return render(request,'SampleManage/retages.html',context)
    if(request.method == 'POST'):
        obj =TagForm(request.POST, request.FILES)
        if obj.is_valid():
            nodename = obj.clean()['nodename']
            timestamp_ = obj.clean()['timestamp']
            timestamp = int(round(time.mktime(timestamp_.timetuple())) * 1000)
            mantag = obj.clean()['mantag']
            result = esinteracton.search_isexist(index="mlganglia_agg",
                                             query_json=esinteracton.search_nodename_timestamp_mantag_queryjson(nodename=nodename,timestamp=timestamp))

            # 搜索结果如果和mantag一致，则不做变化
            if(mantag == str(result)):
                print(nodename, timestamp_, mantag)
                pass
            else:
                isexist = esinteracton.search_isexist(index="mlganglia_agg",
                                                      query_json=esinteracton.is_search_nodename_timestamp_queryjson(nodename=nodename,timestamp=timestamp))
                if(isexist == 0):
                    #如果mlganglia_agg不存在该document，则从search_ganglia查找数据新建
                    mdata = esinteracton.search_bulk(index="search_ganglia",
                                                     query_json=esinteracton.search_nodename_timestamp_queryjson(nodename=nodename,starttime=timestamp,endtime=timestamp,metrics=['time']))
                    esinteracton.insert_bulk(index="mlganglia_agg",mdata=mdata)
                else:
                    pass
                #进行更新操作
                mdata = esinteracton.search_bulk(index="mlganglia_agg",
                                                 query_json=esinteracton.search_nodename_timestamp_queryjson(
                                                     nodename=nodename, starttime=timestamp, endtime=timestamp,
                                                     metrics=['time']))
                if(mantag == '0'):
                    esinteracton.upadte_bulk(index="mlganglia_agg",mdata=mdata,docs={'tags':''})
                else:
                    esinteracton.upadte_bulk(index="mlganglia_agg",mdata=mdata,docs={'tags': 'mantag'})
            print(nodename,timestamp_,mantag)
        return HttpResponse('保存成功')




def predict(request):
    x = []
    y = []
    z = []
    e = []
    anomalypoints = []
    nodename = ''
    metric = ''
    obj = PredictVisForm()
    content = {
               'nodename':nodename,

SampleManage/templates/SampleManage/detect_visualizees.html
{% extends "base.html" %}
{% block title %}
    <title>检测结果可视化</title>
{% endblock %}
{% block mainbody %}
<div style="height: 750px;width: 1400px;margin: auto;top: 0;left: 0;right:0;bottom:0">
    <div style="height:100%;width: 19%;float: left">
       <label style="font-size: 16px">请选择检测条件：</label>
        <form action = "{%url 'SampleManage:detectes' %}" method="post">
          {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="提交">
        </form>
    </div>
<div id="main" style="height:100%;width: 80%;float:right"></div>
</div>
<script type="text/javascript">
    var mycharts = echarts.init(document.getElementById('main'));
    var x = {{ x|safe}};
    var data = {{ y|safe }};
    var predictdata = {{ z|safe }};
    var  error = {{ e|safe }};
    var anomalypoints = {{ anomalypoints|safe }};
    var anomalyscore = {{ anomalyscore|safe }};
    var option = {
         title: {
            text: "{{ nodename }}-{{ metric }}"
            },
            legend: {
             data:['真实值','预测值','偏差','异常候选值','异常分数'],
            },
            tooltip: {
                trigger:'axis',
            },
            dataZoom:[{
                type:'inside',
                start: 0,
                end: 100,
            },
            {
            start: 0,
            end: 10,
            handleSize: '80%',
            handleStyle: {
                color: '#fff',
                shadowBlur: 3,
                shadowColor: 'rgba(0, 0, 0, 0.6)',
                shadowOffsetX: 2,
                shadowOffsetY: 2
             }
            }],
            xAxis: {
                type: 'category',
                data: x
            },
            yAxis: [{
                type: 'value'
            },
                {
                    type:'value'
                 }
                ],
            series: [
                {
                    name:'真实值',
                    data: data,
                    type: 'line',
                    yAxisIndex:0
                    {#markPoint:{#}
                    {#    symbol:'circle',#}
                    {#    symbolSize:10,#}
                    {#    label:{#}
                    {#        show:false,#}
                    {#    },#}
                    {#    itemStyle:{#}
                    {#        color:rgb(128,0,0)#}
                    {##}
                    {#    data:anomalymarkpoints#}
                    {#    },#}
                },
                {
                    name:'预测值',
                    data: predictdata,
                    type:'line',
                    yAxisIndex:0
                },
                {
                    name:'偏差',
                    data:error,
                    type:'line',
                    yAxisIndex:0
                },
                {
                    name:'异常候选值',
                    data :anomalypoints,
                    type:'scatter',
                    yAxisIndex:0
                },
                {
                    name:'异常分数',
                    data:anomalyscore,
                    type:'line',
                    yAxisIndex:1
                }
            ],
};
    mycharts.setOption(option);
    mycharts.on('click', function (param) {
            var myselect = document.getElementById('nodenameid');
            var index = myselect.selectedIndex;
            var nodename = myselect.options[index].text;
            var timestamp = param.name;
            var path = nodename + '/' + timestamp;
            window.open((path + '/retag'));
            {#window.open ((path+'/retag'), '', 'height=200, width=700, top=0, left=0, toolbar=no, menubar=no, scrollbars=no, resizable=no,location=n o, status=no')#}
        });
</script>
{% endblock %}

SampleManage/templates/SampleManage/index.html
{% extends "base.html" %}
{% block mainbody %}
{% endblock %}

SampleManage/templates/SampleManage/mulvisualize.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <script src="{% static 'js/echarts.js' %}"></script>
    <title>多维可视化</title>
</head>
<body>
<form action = "{% url 'SampleManage:mulvisualize' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="提交"/>
</form>

<div id="main" style="width:1980px;height:850px;"></div>
<script type="text/javascript">
    var mycharts = echarts.init(document.getElementById('main'));
    var points = {{ points|safe }};
    var anomalypoints = {{ anomalypoints|safe }};
    var option = {
        title:{
            text:"{{ nodelists }}多维可视化"
        },
        legend:{
            data:['正常点','异常点']
        },
        tooltip:{
            trigger:'axis',
        },
        dataZoom:[{
                type:'inside',
                start: 0,
                end: 100,
            },
            {
            start: 0,
            end: 10,
            handleSize: '80%',
            handleStyle: {
                color: '#fff',
                shadowBlur: 3,
                shadowColor: 'rgba(0, 0, 0, 0.6)',
                shadowOffsetX: 2,
                shadowOffsetY: 2
             }
            }],
        xAxis:{},
        yAxis:{},
        series:[
            {
                symbolSize:2,
                name:'正常点',
                data:points,
                type:'scatter',
            },
            {
                name:'异常点',
                data:anomalypoints,
                type:'scatter',
            },
        ]
    };
    mycharts.setOption(option);
</script>
</body>
</html>

SampleManage/templates/SampleManage/predict.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="{% static 'js/echarts.js' %}"></script>
    <title>预测结果可视化</title>
</head>
<body>
<form action = "{%url 'SampleManage:predict' %}" method="post">
  {% csrf_token %}
    nodename: {{ form.nodenames }} {{ form.errors.nodenames.0 }}
    metric:{{ form.metrics }} {{ form.errors.metrics.0 }}
    trainstart:{{ form.trainstart }} {{ form.errors.trainstart.0 }}
    <input type="submit" value="提交">
</form>
<p>ME:{{me }}</p>
<p>MAE:{{ mae }}</p>
<p>RMSE:{{ rmse }}</p>
<p>MPE:{{ mpe }}</p>
<p>MAPE:{{ mape }}</p>
</body>
</html>

SampleManage/templates/SampleManage/predict_visualize.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="{% static 'js/echarts.js' %}"></script>
    <title>预测结果可视化</title>
</head>
<body>
<form action = "{%url 'SampleManage:predict' %}" method="post">
  {% csrf_token %}
{#    nodename: {{ form.nodenames }} {{ form.errors.nodenames.0 }}#}
{#    metric:{{ form.metrics }} {{ form.errors.metrics.0 }}#}
{#    teststart:{{ form.teststart }} {{ form.errors.teststart.0 }}#}
{#    testend:{{ form.testend }} {{ form.errors.testend.0 }}#}
    {{ form }}
    <input type="submit" value="提交">
</form>
<div id="main" style="width:1980px;height:850px;"></div>
<script type="text/javascript">
    var mycharts = echarts.init(document.getElementById('main'));
    var x = {{ x|safe}};
    var data = {{ y|safe }};
    var predictdata = {{ z|safe }};
    var  error = {{ e|safe }};
    {#var anomalymarkpoints ={{ anomalymarkpoints|safe }};#}
    var anomalypoints = {{ anomalypoints|safe }};
    var option = {
         title: {
            text: "{{ nodename }}-{{ metric }}"
            },
            legend: {
             data:['真实值','预测值','偏差','异常候选值'],
            },
            tooltip: {
                {#trigger:'axis',#}
            },
            dataZoom:[{
                type:'inside',
                start: 0,
                end: 100,
            },
            {
            start: 0,
            end: 10,
            handleSize: '80%',
            handleStyle: {
                color: '#fff',
                shadowBlur: 3,
                shadowColor: 'rgba(0, 0, 0, 0.6)',
                shadowOffsetX: 2,
                shadowOffsetY: 2
             }
            }],
            xAxis: {
                type: 'category',
                data: x
            },
            yAxis: {
                type: 'value'
            },
            series: [
                {
                    name:'真实值',
                    data: data,
                    type: 'line',
                    {#markPoint:{#}
                    {#    symbol:'circle',#}
                    {#    symbolSize:10,#}
                    {#    label:{#}
                    {#        show:false,#}
                    {#    },#}
                        {#itemStyle:{#}
                        {#    color:rgb(128,0,0)#}
                    {##}
                    {#    data:anomalymarkpoints#}
                    {#    },#}
                },
                {
                    name:'预测值',
                    data: predictdata,
                    type:'line'
                },
                {
                    name:'偏差',
                    data:error,
                    type:'line'
                },
                {
                    name:'异常候选值',
                    data :anomalypoints,
                    type:'scatter'
                },
            ],
};
    mycharts.setOption(option);
    mycharts.on('click', function (param) {
            var myselect = document.getElementById('nodenameid');
            var index = myselect.selectedIndex;
            var nodename = myselect.options[index].text;
            var timestamp = param.name;
            var path = nodename + '/' + timestamp;
            window.open((path + '/retag'));
            {#window.open ((path+'/retag'), '', 'height=200, width=700, top=0, left=0, toolbar=no, menubar=no, scrollbars=no, resizable=no,location=n o, status=no')#}
        });
</script>
<p>ME:{{ evamethod.me }}</p>
<p>MAE:{{ evamethod.mae }}</p>
<p>RMSE:{{ evamethod.rmse }}</p>
<p>MPE:{{ evamethod.mpe }}</p>
<p>MAPE:{{ evamethod.mape }}</p>
</body>
</html>

SampleManage/templates/SampleManage/retag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>打标</title>
</head>
<body>
<form name="retagform" action="{% url 'SampleManage:retag' pathtest %}"  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="提交"/>
</form>

</body>
</html>

SampleManage/templates/SampleManage/retages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>人工打标</title>
</head>
<body>
<form name="retagform" action="{% url 'SampleManage:retages' pathtest %}"  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="提交"/>
</form>


</body>
</html>

SampleManage/templates/SampleManage/sample.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <div>
        <form action="{% url 'SampleManage:upload' %}"  class="form-inline" role="form" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="form-group">
            <label class="sr-only" for="inputfile">样本导入</label>
            <input type="file" name="uploadfile">
          <button type="submit" class="btn btn-default">提交</button>
          </div >
       </form>
    </div>
    <br />
    {{ block.super }}
{% endblock %}

SampleManage/templates/SampleManage/testform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <script src="{% static 'js/echarts.js' %}"></script>
</head>

<body>
    <form action = "{%url 'SampleManage:testform' %}" method="post">
          {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="提交">
</body>

</html>